[project]
name = "hacker-news-summarizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "markdown>=3.10",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
]
